{
  "$GMRoomUI":"",
  "%Name":"RoomUI",
  "children":[
    {"$GMRUIFolder":"","%Name":"Folder_1","children":[],"locked":false,"name":"Folder_1","nodeColour":4294068334,"resourceType":"GMRUIFolder","resourceVersion":"2.0","visible":true,},
    {"$GMRUILayer":"v1","%Name":"UILayer_1","alignItems":3,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel_1","alignItems":2,"children":[
            {"$GMRInstance":"v4","%Name":"inst_3134A1EB","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_3134A1EB","objectId":{"name":"obj_ui_controller","path":"objects/obj_ui_controller/obj_ui_controller.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":8.0,"y":8.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":16.0,},"justifyContent":1,"name":"FlexPanel_1","nodeColour":4294107720,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":16.0,},},
        {"$GMRFlexPanel":"","%Name":"FlexPanel","alignItems":2,"children":[
            {"$GMRSpriteGraphic":"v1","%Name":"graphic_2C3F4804","animationSpeed":1.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"headPosition":0.0,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"name":"graphic_2C3F4804","resourceType":"GMRSpriteGraphic","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"spriteId":{"name":"Sprite18","path":"sprites/Sprite18/Sprite18.yy",},"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":285.0,},"justifyContent":1,"name":"FlexPanel","nodeColour":4282970777,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":236.0,},},
        {"$GMRFlexPanel":"","%Name":"Panel_A","alignItems":1,"alignSelf":2,"children":[
            {"$GMRFlexPanel":"","%Name":"Effects","alignItems":4,"children":[
                {"$GMRFlexPanel":"","%Name":"Header","alignItems":2,"children":[],"flexDirection":0,"height":{"unit":1,"value":20.0,},"justifyContent":1,"name":"Header","nodeColour":4282935026,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":1,"value":100.0,},},
                {"$GMRFlexPanel":"","%Name":"Effects_list","alignItems":1,"children":[
                    {"$GMRFlexPanel":"","%Name":"E_1","alignContent":2,"alignItems":4,"children":[
                        {"$GMRFlexPanel":"","%Name":"Img","alignItems":1,"children":[
                            {"$GMRSpriteGraphic":"v1","%Name":"graphic_5312F5A5","animationSpeed":1.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"headPosition":0.0,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"name":"graphic_5312F5A5","resourceType":"GMRSpriteGraphic","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"spriteId":{"name":"Sprite33","path":"sprites/Sprite33/Sprite33.yy",},"x":0.0,"y":0.0,},
                          ],"flexDirection":0,"flexWrap":1,"height":{"unit":3,"value":137.0,},"justifyContent":1,"name":"Img","nodeColour":4290660594,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":163.0,},},
                        {"$GMRFlexPanel":"","%Name":"Description","alignItems":1,"children":[
                            {"$GMRFlexPanel":"","%Name":"Header","alignItems":2,"children":[
                                {"$GMRTextItem":"v3","%Name":"text_6B4A0113","alignment":0,"charSpacing":0.0,"colour":4278190080,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Title_2","path":"fonts/Title_2/Title_2.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_6B4A0113","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Dluuuga noc","wrap":false,"x":0.0,"y":0.0,},
                              ],"flexDirection":0,"height":{"unit":3,"value":27.0,},"justifyContent":1,"name":"Header","nodeColour":4294104392,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":154.0,},},
                            {"$GMRFlexPanel":"","%Name":"Text","alignItems":2,"children":[
                                {"$GMRTextItem":"v3","%Name":"text_5D23E6F8","alignment":0,"charSpacing":0.0,"colour":4279834905,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Content_2","path":"fonts/Content_2/Content_2.yy",},"frameH":90.0,"frameW":376.78577,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_5D23E6F8","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.","wrap":true,"x":0.0,"y":0.0,},
                              ],"flexDirection":0,"height":{"unit":3,"value":18.0,},"justifyContent":1,"name":"Text","nodeColour":4282965490,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":110.0,},},
                          ],"flexDirection":0,"flexWrap":1,"gapRow":6.0,"height":{"unit":3,"value":137.0,},"justifyContent":1,"name":"Description","nodeColour":4290660594,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":163.0,},},
                      ],"flexDirection":2,"flexWrap":1,"height":{"unit":3,"value":100.0,},"justifyContent":1,"name":"E_1","nodeColour":4282970765,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                    {"$GMRFlexPanel":"","%Name":"E_1","alignContent":2,"alignItems":4,"children":[
                        {"$GMRFlexPanel":"","%Name":"Img","alignItems":1,"children":[
                            {"$GMRSpriteGraphic":"v1","%Name":"graphic_474F7ED1","animationSpeed":1.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"headPosition":0.0,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"name":"graphic_474F7ED1","resourceType":"GMRSpriteGraphic","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"spriteId":{"name":"Sprite33","path":"sprites/Sprite33/Sprite33.yy",},"x":0.0,"y":0.0,},
                          ],"flexDirection":0,"flexWrap":1,"height":{"unit":3,"value":137.0,},"justifyContent":1,"name":"Img","nodeColour":4290660594,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":163.0,},},
                        {"$GMRFlexPanel":"","%Name":"Description","alignItems":1,"children":[
                            {"$GMRFlexPanel":"","%Name":"Header","alignItems":2,"children":[
                                {"$GMRTextItem":"v3","%Name":"text_74C9CF53","alignment":0,"charSpacing":0.0,"colour":4278190080,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Title_2","path":"fonts/Title_2/Title_2.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_74C9CF53","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Dluuuga noc","wrap":false,"x":0.0,"y":0.0,},
                              ],"flexDirection":0,"height":{"unit":3,"value":27.0,},"justifyContent":1,"name":"Header","nodeColour":4294104392,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":154.0,},},
                            {"$GMRFlexPanel":"","%Name":"Text","alignItems":2,"children":[
                                {"$GMRTextItem":"v3","%Name":"text_5A86471A","alignment":0,"charSpacing":0.0,"colour":4279834905,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Content_2","path":"fonts/Content_2/Content_2.yy",},"frameH":90.0,"frameW":376.78577,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_5A86471A","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.","wrap":true,"x":0.0,"y":0.0,},
                              ],"flexDirection":0,"height":{"unit":3,"value":18.0,},"justifyContent":1,"name":"Text","nodeColour":4282965490,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":110.0,},},
                          ],"flexDirection":0,"flexWrap":1,"gapRow":6.0,"height":{"unit":3,"value":137.0,},"justifyContent":1,"name":"Description","nodeColour":4290660594,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":163.0,},},
                      ],"flexDirection":2,"flexWrap":1,"height":{"unit":3,"value":100.0,},"justifyContent":1,"name":"E_1","nodeColour":4282970765,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                    {"$GMRFlexPanel":"","%Name":"E_1","alignContent":2,"alignItems":4,"children":[
                        {"$GMRFlexPanel":"","%Name":"Img","alignItems":1,"children":[
                            {"$GMRSpriteGraphic":"v1","%Name":"graphic_56FC7A8","animationSpeed":1.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"headPosition":0.0,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"name":"graphic_56FC7A8","resourceType":"GMRSpriteGraphic","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"spriteId":{"name":"Sprite33","path":"sprites/Sprite33/Sprite33.yy",},"x":0.0,"y":0.0,},
                          ],"flexDirection":0,"flexWrap":1,"height":{"unit":3,"value":137.0,},"justifyContent":1,"name":"Img","nodeColour":4290660594,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":163.0,},},
                        {"$GMRFlexPanel":"","%Name":"Description","alignItems":1,"children":[
                            {"$GMRFlexPanel":"","%Name":"Header","alignItems":2,"children":[
                                {"$GMRTextItem":"v3","%Name":"text_5FB165E9","alignment":0,"charSpacing":0.0,"colour":4278190080,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Title_2","path":"fonts/Title_2/Title_2.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_5FB165E9","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Dluuuga noc","wrap":false,"x":0.0,"y":0.0,},
                              ],"flexDirection":0,"height":{"unit":3,"value":27.0,},"justifyContent":1,"name":"Header","nodeColour":4294104392,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":154.0,},},
                            {"$GMRFlexPanel":"","%Name":"Text","alignItems":2,"children":[
                                {"$GMRTextItem":"v3","%Name":"text_16CCA9ED","alignment":0,"charSpacing":0.0,"colour":4279834905,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Content_2","path":"fonts/Content_2/Content_2.yy",},"frameH":90.0,"frameW":376.78577,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_16CCA9ED","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.","wrap":true,"x":0.0,"y":0.0,},
                              ],"flexDirection":0,"height":{"unit":3,"value":18.0,},"justifyContent":1,"name":"Text","nodeColour":4282965490,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":110.0,},},
                          ],"flexDirection":0,"flexWrap":1,"gapRow":6.0,"height":{"unit":3,"value":137.0,},"justifyContent":1,"name":"Description","nodeColour":4290660594,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":163.0,},},
                      ],"flexDirection":2,"flexWrap":1,"height":{"unit":3,"value":100.0,},"justifyContent":1,"name":"E_1","nodeColour":4282970765,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                    {"$GMRFlexPanel":"","%Name":"E_1","alignContent":2,"alignItems":4,"children":[
                        {"$GMRFlexPanel":"","%Name":"Img","alignItems":1,"children":[
                            {"$GMRSpriteGraphic":"v1","%Name":"graphic_26894ADA","animationSpeed":1.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"headPosition":0.0,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"name":"graphic_26894ADA","resourceType":"GMRSpriteGraphic","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"spriteId":{"name":"Sprite33","path":"sprites/Sprite33/Sprite33.yy",},"x":0.0,"y":0.0,},
                          ],"flexDirection":0,"flexWrap":1,"height":{"unit":3,"value":137.0,},"justifyContent":1,"name":"Img","nodeColour":4290660594,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":163.0,},},
                        {"$GMRFlexPanel":"","%Name":"Description","alignItems":1,"children":[
                            {"$GMRFlexPanel":"","%Name":"Header","alignItems":2,"children":[
                                {"$GMRTextItem":"v3","%Name":"text_39FCC121","alignment":0,"charSpacing":0.0,"colour":4278190080,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Title_2","path":"fonts/Title_2/Title_2.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_39FCC121","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Dluuuga noc","wrap":false,"x":0.0,"y":0.0,},
                              ],"flexDirection":0,"height":{"unit":3,"value":27.0,},"justifyContent":1,"name":"Header","nodeColour":4294104392,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":154.0,},},
                            {"$GMRFlexPanel":"","%Name":"Text","alignItems":2,"children":[
                                {"$GMRTextItem":"v3","%Name":"text_45B86B62","alignment":0,"charSpacing":0.0,"colour":4279834905,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Content_2","path":"fonts/Content_2/Content_2.yy",},"frameH":90.0,"frameW":376.78577,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_45B86B62","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.","wrap":true,"x":0.0,"y":0.0,},
                              ],"flexDirection":0,"height":{"unit":3,"value":18.0,},"justifyContent":1,"name":"Text","nodeColour":4282965490,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":110.0,},},
                          ],"flexDirection":0,"flexWrap":1,"gapRow":6.0,"height":{"unit":3,"value":137.0,},"justifyContent":1,"name":"Description","nodeColour":4290660594,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":163.0,},},
                      ],"flexDirection":2,"flexWrap":1,"height":{"unit":3,"value":100.0,},"justifyContent":1,"name":"E_1","nodeColour":4282970765,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                  ],"flexDirection":0,"flexWrap":1,"height":{"unit":3,"value":140.0,},"justifyContent":0,"layoutDirection":1,"marginTop":{"unit":1,"value":8.0,},"name":"Effects_list","nodeColour":4294073160,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
              ],"flexDirection":0,"gapRow":24.0,"height":{"unit":2,"value":100.0,},"justifyContent":0,"name":"Effects","nodeColour":4288213576,"paddingBottom":{"unit":1,"value":70.0,},"paddingLeft":{"unit":1,"value":70.0,},"paddingRight":{"unit":1,"value":70.0,},"paddingTop":{"unit":1,"value":70.0,},"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":2,"value":60.0,},},
            {"$GMRFlexPanel":"","%Name":"Info","alignItems":2,"children":[],"flexDirection":0,"height":{"unit":2,"value":100.0,},"justifyContent":1,"name":"Info","nodeColour":4288213576,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":2,"value":40.0,},},
            {"$GMRSpriteGraphic":"v1","%Name":"graphic_ECF9F9C","animationSpeed":1.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"headPosition":0.0,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"name":"graphic_ECF9F9C","resourceType":"GMRSpriteGraphic","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"spriteId":{"name":"spr_panel_a","path":"sprites/spr_panel_a/spr_panel_a.yy",},"x":0.0,"y":0.0,},
          ],"flexDirection":2,"flexWrap":1,"height":{"unit":1,"value":775.0,},"justifyContent":0,"name":"Panel_A","nodeColour":4292954354,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":1,"value":1163.0,},},
      ],"flexDirection":0,"gridX":95,"gridY":48,"justifyContent":0,"name":"UILayer_1","nodeColour":4282931954,"paddingRight":{"unit":1,"value":16.0,},"paddingTop":{"unit":1,"value":16.0,},"resourceType":"GMRUILayer","resourceVersion":"2.0",},
  ],
  "locked":false,
  "name":"RoomUI",
  "parent":{
    "name":"Kult_game_0002",
    "path":"Kult_game_0002.yyp",
  },
  "resourceType":"GMRoomUI",
  "resourceVersion":"2.0",
  "viewspaceChildren":[],
  "visible":false,
}